# Generated by Django 3.0 on 2019-12-13 07:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191208_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='type',
        ),
        migrations.AddField(
            model_name='report',
            name='annimal_type',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='sighting_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='summary',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
