# Generated by Django 3.0 on 2019-12-13 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191213_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='animal_type',
            field=models.CharField(choices=[('BEAR', 'Bear'), ('BOBCAT', 'Bobcat'), ('CAT', 'Cat'), ('COYOTEE', 'Coytee'), ('DEER', 'Deer'), ('EAGLE', 'Eagle'), ('EL CHUPACABRA', 'El Chupacabra'), ('MOUNTAIN LION', 'Mountain Lion'), ('WOLF', 'Wolf'), ('OTHER', 'Other')], default='COYOTEE', max_length=20),
        ),
    ]
