# Generated by Django 3.0 on 2019-12-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191213_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='detailed_description',
            field=models.TextField(max_length=1000),
        ),
    ]
